name:                fun-lazy-compiler
version:             0.1.0.0
github:              "jlam55555/fun-lazy-compiler"
license:             BSD3
author:              "Jonathan Lam"
maintainer:          "jlam55555@gmail.com"
copyright:           "2022 Jonathan Lam"

extra-source-files:
- README.md
- JOURNAL.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlam55555/fun-lazy-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- sort == 1.0.0.0
- containers == 0.6.5.1
- hxt == 9.3.1.22               # for Data.AssocList
- split == 0.2.3.4

library:
  source-dirs: src

executables:
  flc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fun-lazy-compiler
    - optparse-applicative >= 0.16 && <= 0.17

tests:
  fun-lazy-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fun-lazy-compiler
    - HUnit == 1.6.2.0
